com.fasterxml.jackson.*:* = 2.21.4
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.google.guava:guava = 33.6.0-jre
com.palantir.gradle.plugintesting:gradle-plugin-testing-junit = 0.69.0
org.assertj:* = 3.27.7
org.immutables:value = 2.12.2
org.junit.jupiter:* = 6.1.2
org.junit.platform:* = 6.1.1
org.junit:junit-bom = 6.1.2
org.mockito:mockito-core = 5.23.0
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.gradle.failure-reports:* = 1.18.0
one.util:streamex = 0.8.4
com.palantir.gradle.idea-configuration:gradle-idea-configuration = 0.8.0

# Unnecessary once we have lock files
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
