com.fasterxml.jackson.*:* = 2.19.2
com.google.guava:guava = 33.4.8-jre
com.netflix.nebula:nebula-dependency-recommender = 13.0.1
org.assertj:* = 3.27.4
org.immutables:value = 2.11.2
org.junit.jupiter:* = 5.13.4
org.junit.platform:* = 1.13.4
org.junit:junit-bom = 5.13.4
org.mockito:mockito-core = 5.18.0
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.gradle.failure-reports:* = 1.2.0
one.util:streamex = 0.8.4
com.palantir.gradle.idea-configuration:gradle-idea-configuration = 0.3.0

# Unnecessary once we have lock files
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
