com.fasterxml.jackson.*:* = 2.19.2
com.google.guava:guava = 31.1-jre
com.netflix.nebula:nebula-dependency-recommender = 11.0.0
org.assertj:* = 3.23.1
org.immutables:value = 2.8.8
org.junit.platform:* = 1.9.1
org.junit:junit-bom = 5.9.1
org.mockito:mockito-core = 4.8.0
com.netflix.nebula:nebula-test = 10.6.2
com.palantir.gradle.failure-reports:* = 1.2.0
one.util:streamex = 0.8.3
com.palantir.gradle.idea-configuration:gradle-idea-configuration = 0.3.0

# Unnecessary once we have lock files
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.11.0
