apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'java-gradle-plugin'
apply plugin: 'com.palantir.gradle-plugin-testing'
apply plugin: 'groovy'

dependencies {
    implementation 'com.google.guava:guava'
    implementation 'com.netflix.nebula:nebula-dependency-recommender'
    implementation 'com.palantir.gradle.failure-reports:gradle-failure-reports-exceptions'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-guava'
    implementation 'one.util:streamex'
    implementation 'com.palantir.gradle.idea-configuration:gradle-idea-configuration'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'

    testImplementation platform('org.junit:junit-bom')
    testImplementation 'com.netflix.nebula:nebula-test'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly "org.junit.vintage:junit-vintage-engine"

    annotationProcessor "org.immutables:value"
    compileOnly "org.immutables:value::annotations"
}

gradlePlugin {
    website = 'https://github.com/palantir/gradle-consistent-versions'
    vcsUrl = 'https://github.com/palantir/gradle-consistent-versions'

    plugins {
        consistentVersions {
            id = 'com.palantir.consistent-versions'
            implementationClass = 'com.palantir.gradle.versions.ConsistentVersionsPlugin'
            displayName = 'Compact, constraint-friendly lockfiles for your dependencies'
            description = displayName
            tags.set(['versions'])
        }
        versionsLock {
            id = 'com.palantir.versions-lock'
            implementationClass = 'com.palantir.gradle.versions.VersionsLockPlugin'
            displayName = 'Compact, constraint-friendly lockfiles for your dependencies'
            description = displayName
            tags.set(['versions'])
        }
        versionsProps {
            id = 'com.palantir.versions-props'
            implementationClass = 'com.palantir.gradle.versions.VersionsPropsPlugin'
            displayName = 'Inject version constraints into every configuration in your projects'
            description = displayName
            tags.set(['versions'])
        }
        versionsPropsIdeaPlugin {
            id = 'com.palantir.version-props-idea'
            implementationClass = 'com.palantir.gradle.versions.VersionsPropsIdeaPlugin'
            displayName = 'Plugin to collect repositories for use by the IDEA plugin.'
            description = displayName
            tags.set(['versions'])
        }
        externallyConsistentVersions {
            id = 'com.palantir.externally-consistent-versions'
            implementationClass = 'com.palantir.gradle.versions.ExternallyConsistentVersionsSettingsPlugin'
            displayName = 'Settings plugin to automatically assign dependencies to a virtual platforms'
            description = displayName
            tags.set(['versions'])
        }
    }
}

afterEvaluate {
    tasks.publishVersionsLockPluginMarkerMavenPublicationToSonatypeRepository.enabled = false
    tasks.publishVersionsPropsPluginMarkerMavenPublicationToSonatypeRepository.enabled = false
}

test {
    jvmArgs '--add-opens', 'java.base/java.lang.invoke=ALL-UNNAMED'
    jvmArgs '--add-opens', 'java.base/java.util=ALL-UNNAMED'
}

gradleTestUtils {
    gradleVersions = ['8.14.3']
}
